use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Subculture {
    pub id: String,
    pub specimen_id: String,
    pub passage_number: i32,
    pub date: String,
    pub media_batch_id: Option<String>,
    pub media_batch_name: Option<String>,
    pub ph: Option<f64>,
    pub temperature_c: Option<f64>,
    pub light_cycle: Option<String>,
    pub light_intensity_lux: Option<f64>,
    pub experimental_treatment: Option<String>,
    pub vessel_type: Option<String>,
    pub vessel_size: Option<String>,
    pub vessel_material: Option<String>,
    pub vessel_lid_type: Option<String>,
    pub location_from: Option<String>,
    pub location_to: Option<String>,
    pub temp_before: Option<f64>,
    pub temp_after: Option<f64>,
    pub humidity_before: Option<f64>,
    pub humidity_after: Option<f64>,
    pub light_before: Option<String>,
    pub light_after: Option<String>,
    pub exposure_duration_hours: Option<f64>,
    pub notes: Option<String>,
    pub observations: Option<String>,
    pub performed_by: Option<String>,
    pub performer_name: Option<String>,
    pub employee_id: Option<String>,
    pub health_status: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Debug, Deserialize)]
pub struct CreateSubcultureRequest {
    pub specimen_id: String,
    pub date: String,
    pub media_batch_id: Option<String>,
    pub ph: Option<f64>,
    pub temperature_c: Option<f64>,
    pub light_cycle: Option<String>,
    pub light_intensity_lux: Option<f64>,
    pub experimental_treatment: Option<String>,
    pub vessel_type: Option<String>,
    pub vessel_size: Option<String>,
    pub vessel_material: Option<String>,
    pub vessel_lid_type: Option<String>,
    pub location_from: Option<String>,
    pub location_to: Option<String>,
    pub temp_before: Option<f64>,
    pub temp_after: Option<f64>,
    pub humidity_before: Option<f64>,
    pub humidity_after: Option<f64>,
    pub light_before: Option<String>,
    pub light_after: Option<String>,
    pub exposure_duration_hours: Option<f64>,
    pub notes: Option<String>,
    pub observations: Option<String>,
    pub employee_id: Option<String>,
    pub health_status: Option<String>,
}

#[derive(Debug, Deserialize)]
pub struct UpdateSubcultureRequest {
    pub id: String,
    pub notes: Option<String>,
    pub observations: Option<String>,
    pub vessel_type: Option<String>,
    pub location_to: Option<String>,
}
